name: CI Pipeline

on:
  push:
    branches:
      - dev
      - staging 
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Application Syntax
        run: |
          python -m py_compile app.py

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Gitleaks Scan
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/path \
          ghcr.io/gitleaks/gitleaks:latest detect \
          --source="/path" \
          --verbose

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'

      - name: Build Docker Image
        run: |
          docker build -t secure-devsecops-app .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secure-devsecops-app'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Run Checkov IaC Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
        continue-on-error: true 
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
      
      - name: Get EC2 Public IP
        id: terraform_output
        run: |
          echo "EC2_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
        working-directory: terraform
  
      - name: Deploy to EC2
          
        env:
          ENVIRONMENT: ${{ github.ref_name }}
       
        uses: appleboy/ssh-action@master

        with:
          host: ${{ env.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
           
            echo "Deploying to $ENVIRONMENT environment"

            cd /home/ubuntu/secure-devsecops-pipeline

            sudo docker stop $(sudo docker ps -q) || true

            sudo docker rm $(sudo docker ps -aq) || true

            sudo docker build -t secure-devsecops-app .

            sudo docker run -d -p 5001:5001 secure-devsecops-app
